# Generated by Django 5.1.2 on 2024-10-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='menu_description',
            field=models.TextField(default='add your description here'),
        ),
    ]
